# gorm配置
[gorm]
# 是否开启调试模式
debug = true
# 数据库类型(目前支持的数据库类型：mysql/sqlite3/postgres)
db_type = "mysql"
# 设置连接可以重用的最长时间(单位：秒)
max_lifetime = 7200
# 设置数据库的最大打开连接数
max_open_conns = 150
# 设置空闲连接池中的最大连接数
max_idle_conns = 50
# 数据库表名前缀
table_prefix = "pa_"

# mysql数据库配置
[mysql]
# 连接地址
host = "39.98.250.155"
# 连接端口
port= 3306
# 用户名
user = "root"
# 密码
password = "gEkYDPloQcp93t4WHr3X"
# 数据库
db_name = "parkassets"
# 连接参数
parameters = "charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"
